### ISSUE TITLE
Erro ao reproduzir a documentação

### ISSUE THREAD

**Issue by vabatista** [jneto04/pToolNER#1]
Ao tentar reproduzir a chamada sequenceTaggingOnTheFly, dá o seguinte erro:

~/ner-flair/pToolNER.py in sequenceTaggingOnTheFly(self, textToPredict, textId, useSentenceTokenize, useTokenizer, maskNamedEntity, createOutputListSpans, createOutputFile, **kwargs)
    402                         sentence = sentence.strip()
    403                         sentenceToPred = Sentence(sentence, use_tokenizer=useTokenizer)
--> 404                         self.tagger.predict(sentenceToPred)
    405
    406                         sentenceSpans = sentenceToPred.get_spans(label_type='label')

AttributeError: 'NoneType' object has no attribute 'predict'

O modelo foi carregado corretamente na linha anterior.

**Comment by jneto04** [comment]
Você poderia mandar um print ou escrever o código da sua chamada do "sequenceTaggingOnTheFly"?

**Comment by vabatista** [comment]
Eu instalei o flair 0.4.1 como nas instruções. Aí tentei carregar o modelo de vocês direto no flair, mas dava erro. Quando atualizei o flair para a versão mais nova, funcionou o método load do SequenceTagging com o 'best-model.pt'

**Comment by jneto04** [comment]
Obrigado por compartilhar a solução.
